spring.application.name=apifamilia
app.frontend-url=http://localhost:4200

spring.security.oauth2.client.registration.google.client-id=1012793755056-0dtcm6bm0pbnr0ttis1ohcvj0ra0sk6r.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email

spring.datasource.url=jdbc:mysql://localhost:3306/familia_db
spring.datasource.username=root
spring.datasource.password=1234567
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always
server.servlet.session.timeout=7d
server.servlet.session.cookie.name=APIFAMILIA_SESSION
server.servlet.session.cookie.max-age=7d
server.servlet.session.cookie.same-site=lax
